[package]
name = "platform_master_rust_edition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez="0.7"
glam = "0.8.5"
rand = "0.8.5"
rand_chacha = "0.3.1"